-- DROP SCHEMA iot;

CREATE SCHEMA iot AUTHORIZATION postgres;

-- DROP SEQUENCE iot.comando_irrigacao_id_seq;

CREATE SEQUENCE iot.comando_irrigacao_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE iot.comando_irrigacao_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE iot.comando_irrigacao_id_seq TO postgres;

-- DROP SEQUENCE iot.configuracao_irrigacao_id_seq;

CREATE SEQUENCE iot.configuracao_irrigacao_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE iot.configuracao_irrigacao_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE iot.configuracao_irrigacao_id_seq TO postgres;

-- DROP SEQUENCE iot.execucao_irrigacao_id_seq;

CREATE SEQUENCE iot.execucao_irrigacao_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE iot.execucao_irrigacao_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE iot.execucao_irrigacao_id_seq TO postgres;

-- DROP SEQUENCE iot.iot_dispositivo_id_seq;

CREATE SEQUENCE iot.iot_dispositivo_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE iot.iot_dispositivo_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE iot.iot_dispositivo_id_seq TO postgres;

-- DROP SEQUENCE iot.leitura_umidade_id_seq;

CREATE SEQUENCE iot.leitura_umidade_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE iot.leitura_umidade_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE iot.leitura_umidade_id_seq TO postgres;
-- iot.iot_dispositivo definição

-- Drop table

-- DROP TABLE iot.iot_dispositivo;

CREATE TABLE iot.iot_dispositivo ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "uuid" uuid NOT NULL, nome varchar(100) NOT NULL, descricao text NULL, token_hash varchar(255) NOT NULL, ativo bool NOT NULL, data_criacao timestamptz NOT NULL, ultimo_contato timestamptz NULL, CONSTRAINT iot_dispositivo_pkey PRIMARY KEY (id), CONSTRAINT iot_dispositivo_token_hash_key UNIQUE (token_hash), CONSTRAINT iot_dispositivo_uuid_key UNIQUE (uuid));
CREATE INDEX iot_dispositivo_token_hash_10a0d2fa_like ON iot.iot_dispositivo USING btree (token_hash varchar_pattern_ops);

-- Permissions

ALTER TABLE iot.iot_dispositivo OWNER TO postgres;
GRANT ALL ON TABLE iot.iot_dispositivo TO postgres;


-- iot.comando_irrigacao definição

-- Drop table

-- DROP TABLE iot.comando_irrigacao;

CREATE TABLE iot.comando_irrigacao ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "uuid" uuid NOT NULL, segundos_irrigacao int4 NOT NULL, status varchar(20) NOT NULL, origem varchar(20) NOT NULL, data_criacao timestamptz NOT NULL, data_envio timestamptz NULL, data_confirmacao timestamptz NULL, observacao text NULL, dispositivo_id int8 NOT NULL, CONSTRAINT comando_irrigacao_pkey PRIMARY KEY (id), CONSTRAINT comando_irrigacao_uuid_key UNIQUE (uuid), CONSTRAINT comando_irrigacao_dispositivo_id_bc2c89c1_fk_iot_dispositivo_id FOREIGN KEY (dispositivo_id) REFERENCES iot.iot_dispositivo(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX comando_irrigacao_dispositivo_id_bc2c89c1 ON iot.comando_irrigacao USING btree (dispositivo_id);
CREATE INDEX idx_comando_disp ON iot.comando_irrigacao USING btree (dispositivo_id);
CREATE INDEX idx_comando_status ON iot.comando_irrigacao USING btree (status);

-- Permissions

ALTER TABLE iot.comando_irrigacao OWNER TO postgres;
GRANT ALL ON TABLE iot.comando_irrigacao TO postgres;


-- iot.configuracao_irrigacao definição

-- Drop table

-- DROP TABLE iot.configuracao_irrigacao;

CREATE TABLE iot.configuracao_irrigacao ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "uuid" uuid NOT NULL, umidade_minima numeric(5, 2) NOT NULL, segundos_irrigacao int4 NOT NULL, intervalo_minimo_minutos int4 NOT NULL, ativo bool NOT NULL, data_criacao timestamptz NOT NULL, dispositivo_id int8 NOT NULL, CONSTRAINT configuracao_irrigacao_pkey PRIMARY KEY (id), CONSTRAINT configuracao_irrigacao_uuid_key UNIQUE (uuid), CONSTRAINT configuracao_irrigac_dispositivo_id_94523d8b_fk_iot_dispo FOREIGN KEY (dispositivo_id) REFERENCES iot.iot_dispositivo(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX configuracao_irrigacao_dispositivo_id_94523d8b ON iot.configuracao_irrigacao USING btree (dispositivo_id);

-- Permissions

ALTER TABLE iot.configuracao_irrigacao OWNER TO postgres;
GRANT ALL ON TABLE iot.configuracao_irrigacao TO postgres;


-- iot.execucao_irrigacao definição

-- Drop table

-- DROP TABLE iot.execucao_irrigacao;

CREATE TABLE iot.execucao_irrigacao ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "uuid" uuid NOT NULL, data_inicio timestamptz NOT NULL, data_fim timestamptz NULL, segundos_executados int4 NULL, sucesso bool NULL, mensagem text NULL, payload_json jsonb NULL, data_registro timestamptz NOT NULL, comando_id int8 NOT NULL, dispositivo_id int8 NOT NULL, CONSTRAINT execucao_irrigacao_pkey PRIMARY KEY (id), CONSTRAINT execucao_irrigacao_uuid_key UNIQUE (uuid), CONSTRAINT execucao_irrigacao_comando_id_e3256022_fk_comando_irrigacao_id FOREIGN KEY (comando_id) REFERENCES iot.comando_irrigacao(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT execucao_irrigacao_dispositivo_id_b469bd3c_fk_iot_dispo FOREIGN KEY (dispositivo_id) REFERENCES iot.iot_dispositivo(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX execucao_irrigacao_comando_id_e3256022 ON iot.execucao_irrigacao USING btree (comando_id);
CREATE INDEX execucao_irrigacao_dispositivo_id_b469bd3c ON iot.execucao_irrigacao USING btree (dispositivo_id);
CREATE INDEX idx_execucao_cmd ON iot.execucao_irrigacao USING btree (comando_id);
CREATE INDEX idx_execucao_disp ON iot.execucao_irrigacao USING btree (dispositivo_id);

-- Permissions

ALTER TABLE iot.execucao_irrigacao OWNER TO postgres;
GRANT ALL ON TABLE iot.execucao_irrigacao TO postgres;


-- iot.leitura_umidade definição

-- Drop table

-- DROP TABLE iot.leitura_umidade;

CREATE TABLE iot.leitura_umidade ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "uuid" uuid NOT NULL, data_hora timestamptz NOT NULL, umidade numeric(5, 2) NOT NULL, bateria numeric(5, 2) NULL, payload_json jsonb NULL, data_recebimento timestamptz NOT NULL, dispositivo_id int8 NOT NULL, CONSTRAINT leitura_umidade_pkey PRIMARY KEY (id), CONSTRAINT leitura_umidade_uuid_key UNIQUE (uuid), CONSTRAINT leitura_umidade_dispositivo_id_6cdab1fd_fk_iot_dispositivo_id FOREIGN KEY (dispositivo_id) REFERENCES iot.iot_dispositivo(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX idx_leitura_data ON iot.leitura_umidade USING btree (data_hora DESC);
CREATE INDEX idx_leitura_disp_data ON iot.leitura_umidade USING btree (dispositivo_id, data_hora DESC);
CREATE INDEX leitura_umidade_dispositivo_id_6cdab1fd ON iot.leitura_umidade USING btree (dispositivo_id);

-- Permissions

ALTER TABLE iot.leitura_umidade OWNER TO postgres;
GRANT ALL ON TABLE iot.leitura_umidade TO postgres;




-- Permissions

GRANT ALL ON SCHEMA iot TO postgres;