# Generated by Django 5.2.13 on 2026-04-30 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"iot"."iot_dispositivo"',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoIrrigacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('umidade_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('segundos_irrigacao', models.IntegerField()),
                ('intervalo_minimo_minutos', models.IntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(db_column='dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='iot.dispositivo')),
            ],
            options={
                'db_table': '"iot"."configuracao_irrigacao"',
            },
        ),
        migrations.CreateModel(
            name='ComandoIrrigacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('segundos_irrigacao', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('EXECUTANDO', 'Executando'), ('FINALIZADO', 'Finalizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('origem', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual'), ('AGENDADO', 'Agendado')], default='AUTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(db_column='dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='iot.dispositivo')),
            ],
            options={
                'db_table': '"iot"."comando_irrigacao"',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoIrrigacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('segundos_executados', models.IntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('comando', models.ForeignKey(db_column='comando_id', on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='iot.comandoirrigacao')),
                ('dispositivo', models.ForeignKey(db_column='dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='iot.dispositivo')),
            ],
            options={
                'db_table': '"iot"."execucao_irrigacao"',
            },
        ),
        migrations.CreateModel(
            name='LeituraUmidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_hora', models.DateTimeField()),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bateria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(db_column='dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='iot.dispositivo')),
            ],
            options={
                'db_table': '"iot"."leitura_umidade"',
            },
        ),
        migrations.AddIndex(
            model_name='comandoirrigacao',
            index=models.Index(fields=['status'], name='idx_comando_status'),
        ),
        migrations.AddIndex(
            model_name='comandoirrigacao',
            index=models.Index(fields=['dispositivo'], name='idx_comando_disp'),
        ),
        migrations.AddIndex(
            model_name='execucaoirrigacao',
            index=models.Index(fields=['dispositivo'], name='idx_execucao_disp'),
        ),
        migrations.AddIndex(
            model_name='execucaoirrigacao',
            index=models.Index(fields=['comando'], name='idx_execucao_cmd'),
        ),
        migrations.AddIndex(
            model_name='leituraumidade',
            index=models.Index(fields=['dispositivo', '-data_hora'], name='idx_leitura_disp_data'),
        ),
        migrations.AddIndex(
            model_name='leituraumidade',
            index=models.Index(fields=['-data_hora'], name='idx_leitura_data'),
        ),
    ]
